name: Comment on pull request

on:
  workflow_run:
    workflows: [Prettier code formatter]
    types:
      - completed

jobs:
  comment:
    # available images: https://github.com/actions/runner-images#available-images
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'failure'
    steps:
      - name: Download artifacts
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: prettier.yml
          workflow_conclusion: failure
          event: pull_request
      - name: PR comment with html diff
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: HTML_Diff/diff.html
          pr_number: $(cat PR/PR.txt)
